// File: app/src/main/java/com/example/apptranslate/model/Language.kt

package com.example.apptranslate.model

import java.util.Locale

// ✨ Bỏ `flagEmoji` ✨
data class Language(
    val code: String,
    val name: String,
    val nativeName: String,
) {
    companion object {
        // ✨ TẠO MỘT DANH SÁCH DUY NHẤT, ĐÃ SẮP XẾP ✨
        val ALL_LANGUAGES: List<Language> = listOf(
            Language("af", "Afrikaans", "Afrikaans"),
            Language("sq", "Albanian", "Shqip"),
            Language("am", "Amharic", "አማርኛ"),
            Language("ar", "Arabic", "العربية"),
            Language("hy", "Armenian", "Հայերեն"),
            Language("az", "Azerbaijani", "Azərbaycan dili"),
            Language("eu", "Basque", "Euskara"),
            Language("be", "Belarusian", "Беларуская"),
            Language("bn", "Bengali", "বাংলা"),
            Language("bs", "Bosnian", "Bosanski"),
            Language("bg", "Bulgarian", "Български"),
            Language("ca", "Catalan", "Català"),
            Language("ceb", "Cebuano", "Cebuano"),
            Language("ny", "Chichewa", "Chichewa"),
            Language("zh-CN", "Chinese (Simplified)", "简体中文"),
            Language("zh-TW", "Chinese (Traditional)", "繁體中文"),
            Language("co", "Corsican", "Corsu"),
            Language("hr", "Croatian", "Hrvatski"),
            Language("cs", "Czech", "Čeština"),
            Language("da", "Danish", "Dansk"),
            Language("nl", "Dutch", "Nederlands"),
            Language("en", "English", "English"),
            Language("eo", "Esperanto", "Esperanto"),
            Language("et", "Estonian", "Eesti"),
            Language("tl", "Filipino", "Filipino"),
            Language("fi", "Finnish", "Suomi"),
            Language("fr", "French", "Français"),
            Language("fy", "Frisian", "Frysk"),
            Language("gl", "Galician", "Galego"),
            Language("ka", "Georgian", "ქართული"),
            Language("de", "German", "Deutsch"),
            Language("el", "Greek", "Ελληνικά"),
            Language("gu", "Gujarati", "ગુજરાતી"),
            Language("ht", "Haitian Creole", "Kreyòl ayisyen"),
            Language("ha", "Hausa", "Hausa"),
            Language("haw", "Hawaiian", "ʻŌlelo Hawaiʻi"),
            Language("iw", "Hebrew", "עברית"),
            Language("hi", "Hindi", "हिन्दी"),
            Language("hmn", "Hmong", "Hmoob"),
            Language("hu", "Hungarian", "Magyar"),
            Language("is", "Icelandic", "Íslenska"),
            Language("ig", "Igbo", "Igbo"),
            Language("id", "Indonesian", "Bahasa Indonesia"),
            Language("ga", "Irish", "Gaeilge"),
            Language("it", "Italian", "Italiano"),
            Language("ja", "Japanese", "日本語"),
            Language("jw", "Javanese", "Basa Jawa"),
            Language("kn", "Kannada", "ಕನ್ನಡ"),
            Language("kk", "Kazakh", "Қазақ тілі"),
            Language("km", "Khmer", "ភាសាខ្មែរ"),
            Language("ko", "Korean", "한국어"),
            Language("ku", "Kurdish (Kurmanji)", "Kurdî (Kurmancî)"),
            Language("ky", "Kyrgyz", "Кыргызча"),
            Language("lo", "Lao", "ລາວ"),
            Language("la", "Latin", "Latina"),
            Language("lv", "Latvian", "Latviešu"),
            Language("lt", "Lithuanian", "Lietuvių"),
            Language("lb", "Luxembourgish", "Lëtzebuergesch"),
            Language("mk", "Macedonian", "Македонски"),
            Language("mg", "Malagasy", "Malagasy"),
            Language("ms", "Malay", "Bahasa Melayu"),
            Language("ml", "Malayalam", "മലയാളം"),
            Language("mt", "Maltese", "Malti"),
            Language("mi", "Maori", "Te Reo Māori"),
            Language("mr", "Marathi", "मराठी"),
            Language("mn", "Mongolian", "Монгол"),
            Language("my", "Myanmar (Burmese)", "ဗမာစာ"),
            Language("ne", "Nepali", "नेपाली"),
            Language("no", "Norwegian", "Norsk"),
            Language("ps", "Pashto", "پښتو"),
            Language("fa", "Persian", "فارسی"),
            Language("pl", "Polish", "Polski"),
            Language("pt", "Portuguese", "Português"),
            Language("pa", "Punjabi", "ਪੰਜਾਬੀ"),
            Language("ro", "Romanian", "Română"),
            Language("ru", "Russian", "Русский"),
            Language("sm", "Samoan", "Gagana faa Samoa"),
            Language("gd", "Scots Gaelic", "Gàidhlig"),
            Language("sr", "Serbian", "Српски"),
            Language("st", "Sesotho", "Sesotho"),
            Language("sn", "Shona", "Chishona"),
            Language("sd", "Sindhi", "سنڌي"),
            Language("si", "Sinhala", "සිංහල"),
            Language("sk", "Slovak", "Slovenčina"),
            Language("sl", "Slovenian", "Slovenščina"),
            Language("so", "Somali", "Soomaali"),
            Language("es", "Spanish", "Español"),
            Language("su", "Sundanese", "Basa Sunda"),
            Language("sw", "Swahili", "Kiswahili"),
            Language("sv", "Swedish", "Svenska"),
            Language("tg", "Tajik", "Тоҷикӣ"),
            Language("ta", "Tamil", "தமிழ்"),
            Language("te", "Telugu", "తెలుగు"),
            Language("th", "Thai", "ไทย"),
            Language("tr", "Turkish", "Türkçe"),
            Language("uk", "Ukrainian", "Українська"),
            Language("ur", "Urdu", "اردو"),
            Language("uz", "Uzbek", "Oʻzbekcha"),
            Language("vi", "Vietnamese", "Tiếng Việt"),
            Language("cy", "Welsh", "Cymraeg"),
            Language("xh", "Xhosa", "Isixhosa"),
            Language("yi", "Yiddish", "ייִדיש"),
            Language("yo", "Yoruba", "Yorùbá"),
            Language("zu", "Zulu", "Isizulu")
        ).sortedBy { it.name }
    }
}